// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: ESP32Clock7inchUI

#ifndef _ESP32CLOCK7INCHUI_UI_H
#define _ESP32CLOCK7INCHUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_TimeWindow
void ui_TimeWindow_screen_init(void);
extern lv_obj_t *ui_TimeWindow;
extern lv_obj_t *ui_MainPanel;
extern lv_obj_t *ui_TimePanel;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_OutTemp;
extern lv_obj_t *ui_pnOutLbl;
extern lv_obj_t *ui_lblOutTemp;
extern lv_obj_t *ui_pnOutImgL;
extern lv_obj_t *ui_OutTempScale;
extern lv_obj_t *ui_pnOutImgR;
extern lv_obj_t *ui_imgOutdor;
extern lv_obj_t *ui_InTemp;
extern lv_obj_t *ui_pnInLbl;
extern lv_obj_t *ui_lblInTemp;
extern lv_obj_t *ui_pnInImgL;
extern lv_obj_t *ui_imginTempSchle;
extern lv_obj_t *ui_pnInImgR;
extern lv_obj_t *ui_imginTempHome;
extern lv_obj_t *ui_InHumi;
extern lv_obj_t *ui_pnLblHum;
extern lv_obj_t *ui_lblInHumi;
extern lv_obj_t *ui_bnHumImgL;
extern lv_obj_t *ui_imgHumi;
extern lv_obj_t *ui_pnHumImgR;
extern lv_obj_t *ui_imgInHumi;
extern lv_obj_t *ui_BrTime;
extern lv_obj_t *ui_pnLblBr;
extern lv_obj_t *ui_LblBrTime;
extern lv_obj_t *ui_pmImgBr;
extern lv_obj_t *ui_BRMap;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_temperatur64_png);   // assets\Temperatur64.png
LV_IMG_DECLARE( ui_img_outdoor48gruen_png);   // assets\OutDoor48Gruen.png
LV_IMG_DECLARE( ui_img_haus48_png);   // assets\Haus48.png
LV_IMG_DECLARE( ui_img_feuchte48_png);   // assets\Feuchte48.png
LV_IMG_DECLARE( ui_img_brasil48_png);   // assets\Brasil48.png

LV_FONT_DECLARE( ui_font_Temp65);
LV_FONT_DECLARE( ui_font_Time150);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
